# -*- coding: utf-8 -*-
"""TASK8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAjxtCRhD1HYo7JJUEexcbvwOWLo8kTk
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("cleaned_superstore.csv")

# Select numerical variables
numeric_data = df[["Sales", "Quantity", "Discount", "Profit"]]

# Calculate correlation
correlation = numeric_data.corr()

print("Correlation Matrix:")
print(correlation)

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap of Superstore Dataset")
plt.show()

"""**Interpretation**

The correlation between Sales and Profit is 0.054, indicating a very weak positive relationship. Quantity and Profit have a weak negative correlation of -0.052, while Discount and Profit have a weak negative correlation of -0.032.

**Three meaningful insights**

**Insight 1 —** Technology performs strongly
Technology generated the highest total sales:
Technology: ₹178,170.36
It also generated the highest total profit:
Technology: ₹45,550.93
Therefore, Technology is the strongest-performing category in this dataset.

**Insight 2 —** Central region has the highest sales
Regional sales are:
Region	Sales
Central	₹140,735.06
East	₹128,554.75
South	₹126,577.72
West	₹113,859.67


The Central region has the highest sales, while the West region has the lowest sales.

**Insight 3 —**  
Sales and Profit are not strongly related
The Sales-Profit correlation is only 0.054.
This indicates that increasing sales alone does not necessarily lead to proportionally higher profit. Other factors such as product category, discount, and product-level profitability may influence profit.
"""