# -*- coding: utf-8 -*-
"""TASK7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xjlW4xt-TP3ytBdTwxkBGMjidEGYbtC
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("cleaned_superstore.csv")

print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nStatistical Summary:")
print(df.describe())


print(df.isnull().sum())

print("Duplicate records:", df.duplicated().sum())

print("Minimum Sales:", df["Sales"].min())
print("Maximum Sales:", df["Sales"].max())

print("Minimum Quantity:", df["Quantity"].min())
print("Maximum Quantity:", df["Quantity"].max())

print("Minimum Discount:", df["Discount"].min())
print("Maximum Discount:", df["Discount"].max())

print("Minimum Profit:", df["Profit"].min())
print("Maximum Profit:", df["Profit"].max())