# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlIOz-N6jMQgYilQfqovpJqRwai6e-1O
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("cleaned_superstore.csv")

# Convert Order Date
df["Order Date"] = pd.to_datetime(df["Order Date"])

# ---------------- LINE CHART ----------------
monthly_sales = df.groupby("Month")["Sales"].sum()

plt.figure(figsize=(8,5))
plt.plot(monthly_sales.index, monthly_sales.values, marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(range(1,13))
plt.grid(True)
plt.show()


# ---------------- BAR CHART ----------------
category_sales = df.groupby("Category")["Sales"].sum()

plt.figure(figsize=(8,5))
plt.bar(category_sales.index, category_sales.values)
plt.title("Sales by Product Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.show()


# ---------------- PIE CHART ----------------
plt.figure(figsize=(7,7))
plt.pie(
    category_sales.values,
    labels=category_sales.index,
    autopct="%1.1f%%"
)
plt.title("Sales Distribution by Category")
plt.show()


# ---------------- HISTOGRAM ----------------
plt.figure(figsize=(8,5))
plt.hist(df["Profit"], bins=20, edgecolor="black")
plt.title("Distribution of Profit")
plt.xlabel("Profit")
plt.ylabel("Frequency")
plt.show()


# ---------------- SCATTER PLOT ----------------
plt.figure(figsize=(8,5))
plt.scatter(df["Sales"], df["Profit"], alpha=0.6)
plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.grid(True)
plt.show()