# -*- coding: utf-8 -*-
"""TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAckSin_D1812rCeWQcZYH3iKUa32Bhc
"""

import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")

quantity = df["Quantity"]

mean = quantity.mean()
median = quantity.median()
mode = quantity.mode()[0]

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)