# -*- coding: utf-8 -*-
"""TASK9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Mdc1u0zTqGENBNuzGLtNkpHdsB379wA

**Recommendation 1:**

Focus on high-performing Technology products
Technology has the highest sales and profit among the three categories. The business should maintain sufficient inventory for popular Technology products and consider targeted promotions for profitable products.
Data support: Technology generated ₹178,170.36 in sales and ₹45,550.93 in profit, the highest among the categories.

**Recommendation 2:**

Improve performance in the West region
The West region generated the lowest sales among the four regions. The business should investigate customer demand, product preferences, pricing, and promotional strategies in this region and introduce targeted marketing campaigns.
Data support: West generated ₹113,859.67, compared with ₹140,735.06 in the Central region.
"""