# -*- coding: utf-8 -*-
"""TASK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9JrKHhAhEgSjypBC5fZZZi4p406SULN
"""

import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")

quantity = df["Quantity"]

correlation = df["Sales"].corr(df["Profit"])

print("Correlation between Sales and Profit:", correlation)
#=======================================================

technology_orders = (df["Category"] == "Technology").sum()
total_orders = len(df)

probability = technology_orders / total_orders

print("Technology orders:", technology_orders)
print("Total orders:", total_orders)
print("Probability:", probability)
print("Probability percentage:", probability * 100, "%")