# -*- coding: utf-8 -*-
"""TASK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLNY1luWJpcZayhtArHOypiULK1n265w
"""

import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")

quantity = df["Quantity"]

variance = quantity.var(ddof=0)
std_deviation = quantity.std(ddof=0)

print("Variance:", variance)
print("Standard Deviation:", std_deviation)