# -*- coding: utf-8 -*-
"""TASK6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX065DJkUmgSQhpjdVKnRVLZSpOEjwiN
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("cleaned_superstore.csv")

# ---------------- COUNT PLOT ----------------
plt.figure(figsize=(8,5))
sns.countplot(data=df, x="Category")
plt.title("Number of Orders by Category")
plt.xlabel("Category")
plt.ylabel("Number of Orders")
plt.show()


# ---------------- BOX PLOT ----------------
plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="Category", y="Profit")
plt.title("Profit Distribution by Category")
plt.xlabel("Category")
plt.ylabel("Profit")
plt.show()


# ---------------- HEATMAP ----------------
numeric_cols = ["Sales", "Quantity", "Discount", "Profit"]
plt.figure(figsize=(8,6))
sns.heatmap(
    df[numeric_cols].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.show()


# ---------------- PAIR PLOT ----------------
sns.pairplot(
    df[["Sales", "Quantity", "Discount", "Profit"]]
)
plt.show()